image: archlinux

secrets:
    - b1dac407-e582-40e8-82e9-b9fda2b105e9

packages:
    - rsync
    - curl
    - clang
    - rust
    - python-setuptools
    - python-ghp-import

sources:
    - https://github.com/bradfier/tibrv-rs

environment:
    TIBRV: $HOME/tibco
    LD_LIBRARY_PATH: $HOME/tibco/lib
    GIT_SSH_COMMAND: '"ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"'

tasks:
    - setup: |
        curl -O https://radio.bradfirj.co.uk/files/tibco.tar.gz
        tar -xf tibco.tar.gz

    - build: |
        cd tibrv-rs
        cargo build --all-features

    - test: |
        cd tibrv-rs
        cargo test --all-features

    - doc: |
        cd tibrv-rs
        if [ "$(git rev-parse master)" = "$(git rev-parse HEAD)" ]; then
          cargo doc --all-features
          echo '<meta http-equiv=refresh content=0;url=tibrv-rs/index.html>' > target/doc/index.html
          ghp-import -n target/doc
          git push ssh://git@github.com/bradfier/tibrv-rs.git gh-pages
        else
          echo "Not on master, skipping..."
        fi
