language: rust
cache: cargo
rust:
    - stable
    - beta
    - nightly

install:
    - curl -O $DEPS
    - tar -xf e19133966fd3bc734c5c033ebecef340.tar.gz

before_script:
    - |
        pip install 'travis-cargo<0.2' --user &&
        export PATH=$HOME/.local/bin:$PATH

script:
    - |
        travis-cargo build -- --all-features &&
        travis-cargo test -- --all-features &&
        travis-cargo --only stable doc -- --all-features

after_success:
    - travis-cargo --only stable doc-upload

env:
    global:
        - TIBRV=$TRAVIS_BUILD_DIR/tibco/
        - LD_LIBRARY_PATH=$TIBRV/lib
        - TRAVIS_CARGO_NIGHTLY_FEATURE=""
